name: FoliaMail
version: 1.2.0
main: dev.user.mailsystem.MailSystemPlugin
api-version: '1.21'
folia-supported: true
depend: [NBTAPI]
softdepend: [XConomy]

commands:
  fmail:
    description: 邮件系统主命令
    aliases: [fmailsystem, fmails, fmsg]
    permission: mailsystem.use
    usage: /fmail <子命令>

permissions:
  mailsystem.use:
    default: true
    description: 使用邮件系统基础功能（打开GUI）
    children:
      mailsystem.read: true
  mailsystem.read:
    default: true
    description: 查看收件箱和阅读邮件
  mailsystem.send:
    default: op
    description: 发送邮件
  mailsystem.attach:
    default: op
    description: 发送带物品附件的邮件
  mailsystem.attach.money:
    default: op
    description: 发送带金币附件的邮件
  mailsystem.delete:
    default: op
    description: 删除自己的邮件
  mailsystem.admin:
    default: op
    description: 邮件系统管理员权限（重载配置、清除缓存等）
  mailsystem.template.create:
    default: op
    description: 创建邮件模板
  mailsystem.template.delete:
    default: op
    description: 删除邮件模板
  mailsystem.template.use:
    default: op
    description: 查看和使用邮件模板
  mailsystem.template.send:
    default: op
    description: 使用模板发送给单个玩家
  mailsystem.template.broadcast:
    default: op
    description: 使用模板群发邮件
